#docker compose for vitejs
# the app is in the same folder as the docker-compose.yml file

version: '3.7'

services:
  app:
    image: node:14
    container_name: vitejs
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn dev"

  