version: '3.1'

services:
    php:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '5656:80'
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
    # TODO: Ajouter la react app(vite)
    app: # is in ./frontend and doesn't need a Dockerfile, it's a vite app. We use yarn, and package.json is in ./frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
        command: yarn dev
        

