version: '3.1'

services:
    backend:
        container_name: Backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '5656:80'
        volumes:
            - ./backend/app:/var/www/html

    db:
        container_name: Database
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./backend/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        container_name: PhpMyAdmin
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1

    frontend:
        container_name: Frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            # use npm instead of yarn
        command: sh -c "npm rebuild esbuild && yarn dev"
        restart: always
        

